services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ../backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    volumes:
      - backend_data:/app

  frontend:
    build: ../frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    # You might need to adjust volumes depending on how you build your Flutter web app
    # volumes:
    #   - ../frontend/build/web:/usr/share/nginx/html:ro

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
  backend_data: