# This Dockerfile is optional as we are using the official ollama image in docker-compose.yml
# You might use this if you need to customize the Ollama image further.
# For now, the docker-compose.yml configuration is sufficient.
